# Source language and JDK version to use.
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties.
install: mvn package cobertura:cobertura coveralls:cobertura -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7} -DserviceJobId=$TRAVIS_JOB_ID
after_success:
  # Get files for use with build, namely the custom Maven settings.xml.
  - "git clone https://github.com/Spoutcraft/travis-ci-resources.git target/travis"
  # Check if commit s not a pull request, if git repo is official, and if branch is master. If checks pass, deploy artifacts to Maven repository.
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == Spoutcraft/SpoutcraftPlugin ]] && [[ $TRAVIS_BRANCH == master ]] && mvn deploy --settings target/travis/settings.xml"
  # TODO: Add deployment to downloads site.

notifications:
  # Disable build status email notifications, until the issue with forks is fixed.
  email: false
  webhooks:
    # Send build information and status to Notifico.
    - http://n.tkte.ch/h/516/9FONea-GLWhZC5VR6mJxlh01

env:
  global:
    - secure: "TSoHaQax6ee65C2I8r/8jazz11/ze+wV8Ipu7wOvibEkUtUxucTpyVXigevswIgDVp/Dk+Gh6SUM1W0pmQhmUkSyW8bjCp7ONWwt0/KxRnTHvcBT22W2MTHbEVQfjNUBvdu5C5NPhlMmHd8NMgwT73P2khnRdFOpsd+lqmxcXww="
    - secure: "iTr7MepCoGSevUTgMkFsO1SrBgitGCBSidocDSjw5TJVjJE3djYI/DfpN3Ys3PlpErVE6omDUTf7gEVSwYHYwKHQ3479+qoVe62wWvwbsY9KAtPnR+l0Fr76o8E4zEERZYzovWHMyz/+10UqvX/OUzWuoVSImV5AmZjCxHylDdI="
