ForceClientKickMessage: This server requires Spoutcraft! http://get.spout.org
ServerVersionCheck: true
ClientCheckTicks: 200
ChunkDataCache: true
AllowClientCache: true
waypoints:
    world:
        Spawn:
            x: 0
            y: 64
            z: 0
    world_nether:
        Spawn:
            x: 0
            y: 64.5
            z: 0
